SET(Tracy_DIR "tracy")
IF(NOT EXISTS ${PROJECT_BINARY_DIR}/Tracy-${CMAKE_BUILD_TYPE}_build)
    EXECUTE_PROCESS(COMMAND mkdir Tracy-${CMAKE_BUILD_TYPE}_build WORKING_DIRECTORY ${PROJECT_BINARY_DIR})
    EXECUTE_PROCESS(COMMAND cmake -DCMAKE_BUILD_TYPE=${CMAKE_BUILD_TYPE}
            -DCMAKE_INSTALL_PREFIX=${PROJECT_BINARY_DIR}/Tracy-${CMAKE_BUILD_TYPE}_build
            ${PROJECT_SOURCE_DIR}/${Tracy_DIR}
             WORKING_DIRECTORY ${PROJECT_BINARY_DIR}/Tracy-${CMAKE_BUILD_TYPE}_build)
    EXECUTE_PROCESS(COMMAND make -j 24 WORKING_DIRECTORY ${PROJECT_BINARY_DIR}/Tracy-${CMAKE_BUILD_TYPE}_build)
ENDIF()
